### PR TITLE
Redesign homepage

### PR DESCRIPTION
**Pull request by wrightmartin**
Added a couple of tweaks that I didnt get to last year

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
Thanks @wrightmartin — any chance of a couple of screenshots to show what this looks like now?

**Comment by wrightmartin** [comment]
@tmtmtmtm here you are

screen shot 2016-01-04 at 16 11 15

**Comment by chrismytton** [comment]
Awesome, thanks @wrightmartin! :+1:

**Comment by tmtmtmtm** [comment]
Thanks @wrightmartin 

The featured person looks a little odd to me, though I'm not sure whether we're going to keep it like that anyway (i.e. whether we're still going to do some sort of carousel thing here) — @chrismytton?

**Comment by chrismytton** [comment]
@tmtmtmtm Yep the plan is to still do a carousel https://github.com/mysociety/kuvakazim/issues/9. I can probably whip up a plugin for that fairly quickly now the design is done.

**Comment by tmtmtmtm** [comment]
I think the old (live) design for the featured person is a lot better than this version:

screen shot 2016-01-04 at 16 51 17

A lot of this is probably just to do with including the summary info, but the arrows for prev/next seem a lot nicer than our version too. Maybe even if "NEXT" were flushed right instead of being immediately after "PREVIOUS" it might be better?

**Comment by chrismytton** [comment]
I've added the summary to the featured person in https://github.com/mysociety/kuvakazim/pull/103. With a bit more details in the box I don't think the prev/next buttons look too bad, but I'll leave the final decision with @wrightmartin!

**Comment by wrightmartin** [comment]
@tmtmtmtm @chrismytton 

I simplified the design of the featured person box, as when it was by itself the page looked unfinished. At the moment, where we don't have any input from the Kuvakazim team I didn't want to start adding new features to the homepage just to make it look right. 

The new styling is temporary, lets re-examine as part of a proper look a the homepage as a whole

**Pull request merged**
